### ISSUE TITLE
Upstream of upstream (Charybdis) is inactive

### ISSUE THREAD

**Issue by janicez** [Elemental-IRCd/elemental-ircd#226]
Just be advised that due to unpleasant treatment by freenode over decisions involving jzk, Charybdis has fallen inactive.

Ja mata!

**Comment by LukeFlynn** [comment]
I've started using InspIRCd because Elemental lacks support for certain IRC v3.2 capabilities that atheme's master has (and then chary lacks a lot of nice elemental features). It's the only happy medium I can find. This is not because I find one or the other superior, it's just a matter of using the right (and active) tool for my particular case. Would love to see this project pick up again.
